name: ubuntu with gfortran
run-name:  is testing ğŸš€
on: [push, pull_request]
jobs:
  test-adv:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }}!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install GFortran Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install gfortran -y
      - name: Install fpm
        run: |
            echo $PATH
            wget https://raw.githubusercontent.com/urbanjost/index/main/bootstrap/fpm.F90
            mkdir -p /home/runner/.local/bin tmp
            gfortran fpm.F90 -Itmp -Jtmp -static -o /home/runner/.local/bin/fpm
            rm -f tmp/*.mod
            ls -l
      - name: ubuntu with gfortran (debug)
        run: |
              fpm test --profile debug --verbose
      - name: æµ‹è¯•ä¸»ç¨‹åº
        run: |
          which gfortran
          make run
